config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :gossips do 
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	validates :anonymous_commentor, presence: true
	validates :body, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :anonymous_author, presence: true
	validates :content, presence: true
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@comment = Comment.new
		puts params.inspect
	end

	def create
		@gossip = Gossip.find(params[:gossip_id])
		@comment = @gossip.comments.create(comment_params)
    	redirect_to gossip_path(@gossip.id)
	end

	def edit
		@gossip = Gossip.find_by(id: params[:gossip_id])
	    @comment = Comment.find(params[:id])
	
	    @anonymous_commentor = @comment.anonymous_commentor
	    @body = @comment.body
	  end

  	def update
	    @comment = Comment.find(params[:id])
	    @comment.update(comment_params)
		redirect_to gossip_path(@comment.gossip_id)
	  end

	 def destroy
	    @comment = Comment.find(params[:id])
	    @comment.destroy
	    redirect_to gossip_path(@comment.gossip_id)
	  end

	private
	def comment_params
		params.require(:comment).permit(:anonymous_commentor, :body)
	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
  	@gossip = Gossip.new
  end

  def create
  	@gossip = Gossip.create(params.permit(:anonymous_author, :content, :id))
    redirect_to gossip_path(@gossip.id)
  end

  def show
  	@gossip= Gossip.find_by(id: params[:id])
  	@anonymous_author = @gossip.anonymous_author
  	@content = @gossip.content
  end

  def index
  	@gossips = Gossip.all
  end

  def edit
    @gossip= Gossip.find_by(id: params[:id])
    @anonymous_author = @gossip.anonymous_author
    @content = @gossip.content
  end

  def update
    @gossip = Gossip.find_by(id: params[:id])
    gossip_params = params.require(:gossip).permit(:anonymous_author, :content)
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def destroy
    @gossip = Gossip.find_by(id: params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/edit.html.erb
<div class="page">
	<h1 class="title">Tu veux modifier ce commentaire ? </h1>


	<%= form_for @comment, url:{action: "update"} do |f| %>
		<p>
			<strong>👤 Pseudo</strong><br>
			<%= f.text_field :anonymous_commentor %>
			<br>
		</p>
		<p>
			<strong>🙉 Commentaire</strong><br>
			<%= f.text_area :body, size: "40x12" %>
			<br>
		</p>
		<%= f.submit "Envoyer" %>
		<% end %>

	<p>
	  <%= link_to 'Supprimer le commentaire', [@comment.gossip, @comment],
	               method: :delete%>
	</p>

</div>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/edit.html.erb
<div class="page">
	<h1 class="title">Tu veux modifier ce gossip ? </h1>


	<%= form_for @gossip do |f| %>
		<p> 
			<strong>👤 Pseudo</strong><br>
	  		<%= f.text_field :anonymous_author %>
	  	</p>
	  	<p>
	  		<strong>🙉 Commentaire</strong><br>
	 		<%= f.text_area :content, size: "40x12" %>
	 	</p>
	  <%= f.submit "Modifier" %>
	<% end %>

	<%= link_to 'Supprimer le gossip', @gossip, method: :delete %>

</div>

app/views/gossips/index.html.erb
<div class="container-fluid page">
	<div class="row">
		<h1 class="title">TOUS LES GOSSIPS</h1>

		<% @gossips.each do |gossip| %>
		<div class="col-lg-3">
			<p>
				<strong>👤 Pseudo</strong>
				<br>
				<%= gossip.anonymous_author %> 
			</p>
			<p>
				<strong>🙈 Gossip</strong>
				<br>
				<%= gossip.content %> 
			</p>
			<a href="/gossips/<%= gossip.id %>/edit" type="button" class="btn btn-primary">Editer</a>
			<a href="<%= gossip_path(gossip.id) %>" type="button" class="btn btn-primary">Voir le gossip</a>
			<p class="small_text"> Commentaires :
			<%= gossip.comments.count %> </p>
		</div>
		<% end %>
	</div>
</div>

app/views/gossips/new.html.erb
<div class="page">
	<p class="title">Quel est ton gossip ?</p>
	<%= form_tag "/gossips", method: "post" do %>
		<p>👤 Pseudo :
	    <input type="text" name="anonymous_author" /></p><br/>
	    <p>🙈 Gossip :
	    <input type="text_area" name="content" size="60x12" /></p><br/>
	    <input type="submit" value="Envoyer" class="btn btn-danger" />
   <% end %>
</div>

app/views/gossips/show.html.erb
<div class="page container">

  <div class="row">
    <h1 class="title">
      Gossip n° <%= @gossip.id %>
    </h1>
    <p class="col-lg-6">👤 <strong> Pseudo </strong><br> <%= @anonymous_author %> </p>
    <p class="col-lg-6">🙊 <strong>Gossip </strong><br><%= @content %></p>
  </div>

  <div class="row">
  <h2 class="title">Tous les commentaires(<%= @gossip.comments.count %>)</h2>
    <% @gossip.comments.each do |comment| %>
    	<div class="col-lg-3">
        <p class="small_text">
      		Commentaire N° : <%= comment.id %>
      	</p>
        <p>
          <strong>👤 Pseudo</strong> :
          <%= comment.anonymous_commentor %>
        </p>
       
        <p>
          <strong>🙉 Commentaire</strong> : 
          <%= comment.body %>
        </p>
        <a href="/gossips/<%= @gossip.id %>/comments/<%= comment.id %>/edit" type="button" class="btn btn-primary">Editer</a>
      </div>
    <% end %>
  </div>


  <div class="row">
    <h2 class="title">Tu veux ajouter un commentaire ?</h2>
    <p class="text">Toi aussi donne nous ton avis !</p>
         <%= form_with(model: [ @gossip, @gossip.comments.build ], local: true) do |form| %>
        <p>
          <%= form.label :anonymous_commentor %><br>
          <%= form.text_field :anonymous_commentor %>
        </p>
        <p>
          <%= form.label :body %><br>
          <%= form.text_area :body %>
        </p>
        <p>
          <%= form.submit %>
        </p>
      <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '/' %></li>
        <li><%= link_to "Index des gossips",  gossips_path %></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Custom Font -->
     <link href="https://fonts.googleapis.com/css?family=Gugi" rel="stylesheet"> 
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 class="title">The Gossip Project</h1>
  <h3>
    Tu as des potins bien croustillants ?
  </h3>
  <p>Viens tout nous raconter par ici</p>
  <%= link_to "💀💀💀💀💀💀💀💀💀💀💀", new_gossip_path , class: "btn btn-lg btn-danger" %>

  <p style="font-size: 12px">Ne t'inquietes pas tout ce que tu nous diras sera anonyme 👤</p>
 
</div>